/**
 * Pace: measure a take that is too slow or padded, then plan the fix.
 *
 * The complaint this answers is "the animation feels rigid, or too slow". Both
 * are measurable on the take itself, before anything is rendered:
 *
 *  - SLOW is dead air: frames where nothing happens, most often before the
 *    first move and after the last one. A generated take that opens and closes
 *    on two seconds of standing still reads as a loading screen.
 *  - RIGID is a take that only ever crawls: its whole root speed sits under a
 *    walking pace. A performer reaching for a cup accelerates and decelerates;
 *    a take that never exceeds 0.1 m/s reads as a mannequin on a rail.
 *
 * The fix is the studio's OWN mechanism, not a new one. `motion-edit.js` already
 * holds a take as ordered source segments, each with a `speed`, and
 * `renderMotionEdit` re-encodes them through `retimeMotion` — slerped
 * rotations, joint positions regenerated by forward kinematics, bone lengths
 * exact. That path is persisted with the project, undoable, and already
 * reachable by the agent (`motion.setSegmentSpeed`). So this module does NOT
 * move a single vertex: it measures, and it decides which source range to play
 * at which speed.
 *
 * Why that is the safe shape. A segment list is a partition of source frames
 * into contiguous, non-overlapping ranges. Playing them in order means every
 * pose of the action is still shown, still in order — a hand that lets go of a
 * prop cannot be made to grab it again, and a foot contact cannot be skipped —
 * while the time spent on each range changes. That is the whole safety
 * argument, and it comes free from the data structure rather than from a
 * promise in a comment.
 *
 * Nothing here touches the renderer, the store or the network.
 */

import { CSKEL27_JOINTS } from "./cskel27.js";
import { deriveBoneOffsets, forwardKinematics } from "./convert.js";
import { canonicalCskel27Reference } from "./to-cskel27.js";

const JOINTS = CSKEL27_JOINTS.length;

/** Below this many frames a take has nothing to redistribute. */
export const PACE_MIN_FRAMES = 8;
/** Root speed (m/s) under which a frame counts as standing still. A person
 * shifting their weight moves the hips about a centimetre; below that the take
 * is holding still. */
export const STILL_SPEED = 0.02;
/** Above this share of still frames the take reads as padded. */
export const DEAD_AIR_SHARE = 0.25;
/** A take that never exceeds this, on its own moving frames, reads as sluggish. */
export const SLUGGISH_SPEED = 0.18;
/** The fastest this module will ask for. The editor allows 4x; beyond about
 * double, a walk stops reading as a walk, and "faster" becomes a different
 * performance rather than a better-paced one. */
export const MAX_PACE_SPEED = 2;
/** The studio's own grid and floor (`motion-edit.js` SPEED_STEP / SPEED_MIN). */
export const SPEED_STEP = 0.1;
export const SPEED_MIN = 1;

const BONE_OFFSETS = (() => {
	const skeleton = canonicalCskel27Reference();
	return deriveBoneOffsets(skeleton.posed_joints, skeleton.local_rot_mats);
})();

/** Root displacement between consecutive frames, in metres per second, from the
 * take's own `rootPos`. One entry per interval, so `frames - 1` of them. */
export function rootSpeeds(motion, fps = motion?.fps) {
	const frames = Number(motion?.frames);
	if (!Number.isInteger(frames) || frames < 2) return [];
	const rate = Number(fps);
	if (!Number.isFinite(rate) || rate <= 0) return [];
	// A motion without a root trajectory is not a motion this module can judge:
	// returning "no speeds" leaves the take alone, where guessing a speed of
	// zero would report it as dead air and offer to trim a pose it never read.
	const root = motion.rootPos;
	if (!root || typeof root.length !== "number" || root.length < frames * 3) return [];
	const out = new Array(frames - 1);
	for (let f = 0; f < frames - 1; f += 1) {
		const a = f * 3;
		const b = (f + 1) * 3;
		const dx = motion.rootPos[b] - motion.rootPos[a];
		const dz = motion.rootPos[b + 2] - motion.rootPos[a + 2];
		out[f] = Math.hypot(dx, dz) * rate;
	}
	return out;
}

/**
 * What is wrong with this take's pace, in numbers a caller can act on.
 *
 * `meanMovingSpeed` deliberately ignores standing frames: averaging them in
 * would call a two-second pause inside a three-second walk "a slow walk", when
 * the walk itself is fine and the pause is the problem.
 */
export function analyzePacing(motion, { fps = motion?.fps, stillSpeed = STILL_SPEED } = {}) {
	const frames = Number(motion?.frames) || 0;
	const speeds = rootSpeeds(motion, fps);
	const moving = speeds.filter((speed) => speed > stillSpeed);
	const mean = (values) => (values.length ? values.reduce((total, value) => total + value, 0) / values.length : 0);
	const seconds = Number.isFinite(fps) && fps > 0 ? frames / fps : 0;
	const stillShare = speeds.length ? (speeds.length - moving.length) / speeds.length : 0;
	// Dead air is measured at the ENDS. A pause in the middle of a gesture is a
	// beat the performer chose; a take that opens and closes on nothing is the
	// take's own padding.
	const leading = speeds.findIndex((speed) => speed > stillSpeed);
	const trailing = speeds.slice().reverse().findIndex((speed) => speed > stillSpeed);
	const leadingStillIntervals = leading === -1 ? speeds.length : leading;
	const trailingStillIntervals = speeds.length === 0 ? 0 : trailing === -1 ? speeds.length : trailing;
	const issues = [];
	if (frames >= PACE_MIN_FRAMES && speeds.length) {
		if (stillShare > DEAD_AIR_SHARE) issues.push("dead-air");
		if (moving.length && mean(moving) < SLUGGISH_SPEED) issues.push("sluggish");
		if (leadingStillIntervals + trailingStillIntervals > speeds.length * 0.4) issues.push("padded-ends");
	}
	return {
		frames,
		fps: Number.isFinite(fps) ? fps : null,
		seconds,
		speeds,
		stillShare,
		leadingStillFrames: leadingStillIntervals,
		trailingStillFrames: trailingStillIntervals === speeds.length ? 0 : trailingStillIntervals,
		meanMovingSpeed: mean(moving),
		issues,
		verdict: issues.length ? issues.join(", ") : "even",
	};
}

/** Round a speed onto the studio's grid, never below 1x: this module speeds a
 * take up, it never slows one down. Speeding a performance down to "fix" it
 * would be inventing time the take does not have. */
export function quantizeSpeed(value) {
	const clamped = Math.min(MAX_PACE_SPEED, Math.max(SPEED_MIN, Number(value) || SPEED_MIN));
	return Number((Math.round(clamped / SPEED_STEP) * SPEED_STEP).toFixed(2));
}

/**
 * The source range that holds the action: everything the take does that is not
 * padding. Returned in SOURCE frame indices, inclusive.
 *
 * The interval `f` covers frames `f` to `f + 1`, so a leading run of `lead`
 * still intervals ends at frame `lead`, and a trailing run of `tail` begins at
 * `frames - 1 - tail`. Returning the shared boundary this way keeps the first
 * and last real poses of the action inside the plan.
 */
export function actionRange(pacing, { trimEnds = true, stillSpeed = STILL_SPEED } = {}) {
	const frames = pacing?.frames ?? 0;
	if (!Number.isInteger(frames) || frames < 2) return null;
	// A take in which NOTHING moves has no action to keep. Offering a range here
	// would let a plan trim a still take down to a still take, reporting a
	// change where none is possible — and the honest answer to "this take does
	// not move" is a refusal, not a shorter nothing.
	const speeds = Array.isArray(pacing.speeds) ? pacing.speeds : [];
	const firstMove = speeds.findIndex((speed) => speed > stillSpeed);
	if (firstMove === -1) return null;
	const lead = trimEnds ? pacing.leadingStillFrames : 0;
	const tail = trimEnds ? pacing.trailingStillFrames : 0;
	const sourceStart = Math.max(0, Math.min(lead, frames - 2));
	const sourceEnd = Math.max(sourceStart + 1, Math.min(frames - 1, frames - 1 - tail));
	if (sourceEnd - sourceStart < 1) return null;
	return { sourceStart, sourceEnd, trimmedLead: lead, trimmedTail: tail };
}

/**
 * The segment plan for a take, or null when there is nothing worth changing.
 *
 * One segment is enough and one segment is safest: a single range played at one
 * speed cannot reorder anything, and it keeps the edit legible in the take bar
 * (one row the user can drag, not a dozen). The speed is chosen to bring the
 * take's own moving average up to a walking pace — so a take that is merely
 * padded keeps 1x and only loses its dead air, while a take that truly crawls
 * is compressed `until it reads as movement.
 *
 * `speedup` overrides that choice when the user asks for a specific factor.
 */
export function paceSegments(motion, { fps = motion?.fps, speedup = null, trimEnds = true, stillSpeed = STILL_SPEED } = {}) {
	const pacing = analyzePacing(motion, { fps, stillSpeed });
	if (!pacing.issues.length) return null;
	const range = actionRange(pacing, { trimEnds });
	if (!range) return null;
	const asked = Number(speedup);
	// A sluggish take is brought back to a walking pace; a padded one is only
	// trimmed. An explicit request always wins, inside the module's cap.
	const derived = pacing.meanMovingSpeed > 0 ? SLUGGISH_SPEED / pacing.meanMovingSpeed : 1;
	const speed = quantizeSpeed(Number.isFinite(asked) && asked > 0 ? asked : Math.max(1, derived));
	const trimmed = range.sourceStart > 0 || range.sourceEnd < pacing.frames - 1;
	if (speed === 1 && !trimmed) return null;
	const removedSeconds = (range.trimmedLead + range.trimmedTail) / (pacing.fps || 24);
	return {
		segments: [{ id: "pace-0", sourceStart: range.sourceStart, sourceEnd: range.sourceEnd, speed }],
		pacing,
		speed,
		trimmedLeadFrames: range.trimmedLead,
		trimmedTailFrames: range.trimmedTail,
		summary: speed > 1
			? `Played the take at ${speed.toFixed(1)}x${trimmed ? ` and dropped ${removedSeconds.toFixed(2)}s of still frames` : ""}.`
			: `Dropped ${removedSeconds.toFixed(2)}s of still frames at the ends; the action itself is unchanged.`,
	};
}

export { forwardKinematics, BONE_OFFSETS, JOINTS };
