/**
 * Pacing: a take that is too slow, or that starts and ends with dead air.
 *
 * The complaint this answers is "the animation feels rigid, or too slow". Both
 * are measurable on the take itself, before any rendering:
 *
 *  - RIGID is a take that barely moves at all: most root speed sits in a narrow
 *    band, or the whole clip is slower than a person would move. A performer
 *    reaching for a cup accelerates and decelerates; a take that only ever
 *    crawls reads as a mannequin being slid along a rail.
 *  - SLOW is dead air: frames where nothing happens, most often before the
 *    first move and after the last one.
 *
 * The fix is a monotone time-warp — a mapping from output time to source time
 * that never runs backwards, keeps the first and last frames where they are,
 * and can only redistribute time between them. Monotonicity is the whole
 * safety argument: every pose being held mid-way through is still passed
 * through, in the same order, so a pose key, a foot contact or a hand on a
 * prop cannot end up skipped by speeding past it. Time is compressed or
 * stretched WITHIN those constraints; the take is never re-timed backwards.
 *
 * Rotations travel by slerp and joint positions are regenerated by forward
 * kinematics, exactly as `retime.js` does — a lerped position beside a slerped
 * rotation is what makes feet tremble, and this module exists to make a take
 * look better, not worse.
 *
 * Nothing here touches the renderer, the store or the network.
 */

import { CSKEL27_JOINTS } from "./cskel27.js";
import { deriveBoneOffsets, forwardKinematics, matToQuat, quatToMat } from "./convert.js";
import { canonicalCskel27Reference } from "./to-cskel27.js";
import { slerpQuat } from "./retime.js";

const JOINTS = CSKEL27_JOINTS.length;

/** Below this many frames a warp has nothing to redistribute. */
export const PACE_MIN_FRAMES = 8;
/** Root speed (m/s) under which a frame counts as standing still. A person
 * shifting their weight moves the hips ~1 cm; below that the take is holding. */
export const STILL_SPEED = 0.02;
/** Above this share of still frames the take reads as padded. */
export const DEAD_AIR_SHARE = 0.25;
/** A take slower than this, on its own moving frames, reads as sluggish. */
export const SLUGGISH_SPEED = 0.18;
/** How much of a clip the warp may remove at most. Beyond this the take is not
 * slow, it is a different shot, and trimming it is the user's call. */
export const MAX_SPEEDUP = 0.5;
/** The most the warp may stretch a clip. Never used for speeding up, only to
 * keep a dominated segment from collapsing to a single output frame. */
export const MAX_SLOWDOWN = 2;

const BONE_OFFSETS = (() => {
	const skeleton = canonicalCskel27Reference();
	return deriveBoneOffsets(skeleton.posed_joints, skeleton.local_rot_mats);
})();

/** Root displacement between frames, in metres, from the take's own rootPos. */
export function rootSpeeds(motion, fps = motion?.fps) {
	const frames = Number(motion?.frames);
	if (!Number.isInteger(frames) || frames < 2) return [];
	const rate = Number(fps);
	if (!Number.isFinite(rate) || rate <= 0) return [];
	const out = new Array(frames - 1);
	for (let f = 0; f < frames - 1; f += 1) {
		const a = f * 3;
		const b = (f + 1) * 3;
		const dx = motion.rootPos[b] - motion.rootPos[a];
		const dz = motion.rootPos[b + 2] - motion.rootPos[a + 2];
		out[f] = Math.hypot(dx, dz) * rate;
	}
	return out;
}

/** The share of `values` at or below `threshold`. */
function shareAtOrBelow(values, threshold) {
	if (!values.length) return 0;
	return values.filter((value) => value <= threshold).length / values.length;
}

/**
 * What is wrong with this take's pace, in numbers a caller can act on.
 *
 * `moving` frames are the ones with a real root speed; `still` counts the rest.
 * `meanMovingSpeed` deliberately ignores standing frames: averaging them in
 * would call a 2-second pause in a 3-second walk "a slow walk", when the walk
 * itself is fine and the pause is the problem.
 */
export function analyzePacing(motion, { fps = motion?.fps, stillSpeed = STILL_SPEED } = {}) {
	const frames = Number(motion?.frames) || 0;
	const speeds = rootSpeeds(motion, fps);
	const moving = speeds.filter((speed) => speed > stillSpeed);
	const mean = (values) => (values.length ? values.reduce((total, value) => total + value, 0) / values.length : 0);
	const seconds = Number.isFinite(fps) && fps > 0 ? frames / fps : 0;
	const stillShare = speeds.length ? (speeds.length - moving.length) / speeds.length : 0;
	// Dead air is measured at the ENDS only: a pause in the middle of a gesture
	// is a beat the performer chose, while a take that opens and closes on
	// nothing is the take's padding.
	const leading = speeds.findIndex((speed) => speed > stillSpeed);
	const trailing = speeds.slice().reverse().findIndex((speed) => speed > stillSpeed);
	const leadingStill = leading === -1 ? speeds.length : leading;
	const trailingStill = trailing === -1 ? speeds.length : trailing;
	const trailingTail = trailingStill === 0 ? 0 : Math.min(trailingStill, speeds.length - 1);
	const issues = [];
	if (frames >= PACE_MIN_FRAMES) {
		if (stillShare > DEAD_AIR_SHARE) issues.push("dead-air");
		if (moving.length && mean(moving) < SLUGGISH_SPEED) issues.push("sluggish");
		if (speeds.length && leadingStill + trailingTail > speeds.length * 0.4) issues.push("padded-ends");
	}
	return {
		frames,
		fps: Number.isFinite(fps) ? fps : null,
		seconds,
		speeds,
		stillShare,
		leadingStillFrames: leadingStill,
		trailingStillFrames: frames >= 2 ? trailingTail : 0,
		meanMovingSpeed: mean(moving),
		issues,
		verdict: issues.length ? issues.join(", ") : "even",
	};
}

/**
 * A monotone time warp built for one take.
 *
 * The map is piecewise linear over the take's own frames: `at(i)` answers which
 * SOURCE time (in frames, fractional) output frame `i` should show. Three rules
 * are structural, not tunable:
 *
 *  1. strictly non-decreasing — the output never runs backwards;
 *  2. `at(0) === 0` and `at(outFrames - 1) === frames - 1` when `keepEnds` is
 *     set, so the take still starts and ends on the same poses;
 *  3. the FIRST and LAST moving frames are pinned, which is what preserves the
 *     entry and exit poses of an action rather than clipping its wind-up.
 */
export function buildPaceWarp(pacing, { frames = pacing?.frames, fps = pacing?.fps, speedup = null, trimEnds = true } = {}) {
	const total = Number(frames) || 0;
	if (!Number.isInteger(total) || total < PACE_MIN_FRAMES) return null;
	if (typeof pacing?.at !== "function" && !Array.isArray(pacing?.speeds)) return null;
	const distances = pacing.speeds;
	// The frame where the take first really moves, and the last one. Between
	// them is the action; outside them is padding.
	const first = Math.max(0, distances.findIndex((speed) => speed > STILL_SPEED));
	let last = distances.length - 1;
	while (last > first && !(distances[last] > STILL_SPEED)) last -= 1;
	if (last <= first) return null; // nothing ever moves: no pace to fix
	const lead = trimEnds ? first : 0;
	const tail = trimEnds ? distances.length - 1 - last : 0;

	// Every interval keeps a SHARE of its time, never zero. That is the whole
	// safety argument: a strictly increasing clock can only ever resample the
	// take, so every pose is still passed through, in order, and no pose key,
	// foot contact or hand on a prop can be stepped over by "speeding past" it.
	//
	//  - A STILL interval — dead air, before or inside the action — keeps the
	//    smallest share: this is where the shortness comes from.
	//  - A MOVING interval keeps its speed over the take's own average, capped at
	//    1: a stretch already at the average is left exactly alone, which is what
	//    makes a take look less sluggish rather than sped up.
	const STILL_SHARE = 0.2;
	const MIN_MOVING_SHARE = 0.35;
	const floorWeight = STILL_SHARE;
	const target = pacing.meanMovingSpeed > 0 ? pacing.meanMovingSpeed : SLUGGISH_SPEED;
	const weights = new Array(distances.length);
	for (let f = 0; f < distances.length; f += 1) {
		const speed = distances[f];
		weights[f] = speed > STILL_SPEED
			? Math.max(MIN_MOVING_SHARE, Math.min(1, speed / target))
			: STILL_SHARE;
	}

	// Cumulative "kept time" at every source frame: the warp's own clock, in
	// source frames. Strictly increasing, because no interval is worth zero.
	const wanted = Number(speedup);
	const scale = Number.isFinite(wanted) && wanted > 0 ? Math.min(MAX_SLOWDOWN, Math.max(1 - MAX_SPEEDUP, wanted)) : 1;
	const cumulative = new Array(total);
	cumulative[0] = 0;
	for (let s = 0; s < total - 1; s += 1) cumulative[s + 1] = cumulative[s] + weights[s] * scale;
	const kept = cumulative[total - 1];
	if (!(kept > 0)) return null;

	// The output length is the kept time itself, so no output frame repeats a
	// source instant, and — because cumulative[0] is 0 and cumulative[total-1]
	// is `kept` — the take still begins and ends on its own first and last
	// poses. Nothing outside this function has to know the take was retimed.
	const outFrames = Math.max(2, Math.round(kept) + 1);
	const step = kept / (outFrames - 1);
	const at = (index) => {
		const clamped = Math.max(0, Math.min(outFrames - 1, Number(index) || 0));
		if (clamped === 0) return 0;
		if (clamped === outFrames - 1) return total - 1;
		const want = clamped * step;
		// First source frame whose kept time has passed `want`, then the fraction
		// between it and the one before it. Landing between two source frames is
		// what makes the motion accelerate smoothly instead of stepping.
		let high = 1;
		while (high < total - 1 && cumulative[high] <= want) high += 1;
		const low = high - 1;
		const span = cumulative[high] - cumulative[low];
		const fraction = span > 0 ? (want - cumulative[low]) / span : 0;
		return low + Math.max(0, Math.min(1, fraction));
	};

	return {
		at,
		outFrames,
		sourceFrames: total,
		leadingStillFrames: lead,
		trailingStillFrames: tail,
		innerStillFrames: distances.slice(lead, last + 1).filter((speed) => speed <= STILL_SPEED).length,
		fps: Number.isFinite(fps) ? fps : null,
		scale,
		keptFrames: kept,
	};
}

function readMat(flat, offset) {
	return [[flat[offset], flat[offset + 1], flat[offset + 2]], [flat[offset + 3], flat[offset + 4], flat[offset + 5]], [flat[offset + 6], flat[offset + 7], flat[offset + 8]]];
}

function writeMat(flat, offset, m) {
	flat[offset] = m[0][0]; flat[offset + 1] = m[0][1]; flat[offset + 2] = m[0][2];
	flat[offset + 3] = m[1][0]; flat[offset + 4] = m[1][1]; flat[offset + 5] = m[1][2];
	flat[offset + 6] = m[2][0]; flat[offset + 7] = m[2][1]; flat[offset + 8] = m[2][2];
}

function readLocals(flat, frame) {
	const locals = new Array(JOINTS);
	for (let j = 0; j < JOINTS; j += 1) locals[j] = readMat(flat, (frame * JOINTS + j) * 9);
	return locals;
}

/**
 * A take resampled through a warp. Rotations slerp between the two source
 * frames the warp lands between, joint positions are regenerated by forward
 * kinematics from those rotations (feet keep their bone lengths), and the root
 * lerps. Every other field rides through, `anchorFrame` included once mapped.
 *
 * The caller gets a motion of exactly `warp.outFrames` frames: the duration
 * changed, which is the point — the take now spends its time where the action
 * is.
 */
export function warpMotion(motion, warp) {
	if (!motion || !warp || typeof warp.at !== "function") throw new Error("warpMotion needs a motion and a built warp");
	const source = Number(motion.frames);
	if (!Number.isInteger(source) || source < 2) throw new Error("warpMotion: motion.frames must be an integer of at least 2");
	const frames = warp.outFrames;
	const rotMats = new Float32Array(frames * JOINTS * 9);
	const rootPos = new Float32Array(frames * 3);
	const posedJoints = new Float32Array(frames * JOINTS * 3);

	for (let f = 0; f < frames; f += 1) {
		const s = Math.max(0, Math.min(source - 1, warp.at(f)));
		const i0 = Math.min(Math.floor(s), source - 1);
		const i1 = Math.min(i0 + 1, source - 1);
		const t = Math.max(0, Math.min(1, s - i0));
		const exact = t === 0 || i0 === i1;
		for (let j = 0; j < JOINTS; j += 1) {
			const dst = (f * JOINTS + j) * 9;
			const src0 = (i0 * JOINTS + j) * 9;
			if (exact) { for (let k = 0; k < 9; k += 1) rotMats[dst + k] = motion.rotMats[src0 + k]; continue; }
			const q = slerpQuat(matToQuat(readMat(motion.rotMats, src0)), matToQuat(readMat(motion.rotMats, (i1 * JOINTS + j) * 9)), t);
			writeMat(rotMats, dst, quatToMat(q));
		}
		for (let axis = 0; axis < 3; axis += 1) {
			rootPos[f * 3 + axis] = motion.rootPos[i0 * 3 + axis] * (1 - t) + motion.rootPos[i1 * 3 + axis] * t;
		}
		const positions = forwardKinematics(readLocals(rotMats, f), BONE_OFFSETS, [rootPos[f * 3], rootPos[f * 3 + 1], rootPos[f * 3 + 2]]);
		for (let j = 0; j < JOINTS; j += 1) {
			const pd = (f * JOINTS + j) * 3;
			posedJoints[pd] = positions[j][0];
			posedJoints[pd + 1] = positions[j][1];
			posedJoints[pd + 2] = positions[j][2];
		}
	}

	const warped = { ...motion, frames, rotMats, rootPos, posedJoints };
	if (Number.isFinite(motion.anchorFrame)) {
		// The anchor is a source frame; map it to the output frame that shows it.
		// Scanning forward is exact and cheap, and a warp is monotone so the
		// answer is unique.
		let mapped = 0;
		for (let f = 0; f < frames; f += 1) { if (warp.at(f) <= motion.anchorFrame) mapped = f; else break; }
		warped.anchorFrame = mapped;
	}
	return warped;
}

/**
 * The whole pass in one call: measure, build, apply. Returns the take plus what
 * was done to it, so a caller can report the change instead of silently
 * swapping the user's animation.
 *
 * A take with nothing to fix returns `{ motion, changed: false }` and the SAME
 * object — a no-op must not look like an edit in the history.
 */
export function tightenPacing(motion, { fps = motion?.fps, speedup = null, trimEnds = true, stillSpeed = STILL_SPEED } = {}) {
	const pacing = analyzePacing(motion, { fps, stillSpeed });
	if (!pacing.issues.length) return { motion, pacing, warp: null, changed: false };
	const warp = buildPaceWarp(pacing, { frames: pacing.frames, fps: pacing.fps, speedup, trimEnds });
	if (!warp || warp.outFrames >= pacing.frames) return { motion, pacing, warp, changed: false };
	const warped = warpMotion(motion, warp);
	return {
		motion: warped, pacing, warp, changed: true,
		summary: `Shortened ${(pacing.frames / (pacing.fps || 24)).toFixed(2)}s to ${(warped.frames / (pacing.fps || 24)).toFixed(2)}s by removing ${pacing.leadingStillFrames} leading and ${pacing.trailingStillFrames} trailing still frames, and compressing the slowest stretches.`,
	};
}
