// Pace: make a take read more dynamically without generating anything again.
//
// The measurement and the plan live in `src/ardy/pace.js` and are pure. This
// module is the command surface, and it encodes nothing by hand: it hands the
// plan to the studio's OWN segment writer, the very one `motion.setSegmentSpeed`
// drives. That choice is the whole design —
//
//  * every pose of the action is still shown, in order, because a segment list
//    is a partition of the source played front to back;
//  * the change is one undoable entry, like any other authored edit, because a
//    mutation is what this registers as;
//  * it persists with the project for free, since it writes the same field;
//  * nothing is generated, so it costs no credits and needs no AI backend.
//
// The take is measured on its UNTRIMMED source (`fullMotionFor`). A segment
// plan is expressed in source frames, so measuring an already-trimmed render
// would describe the current edit instead of the performance — and a second
// tightening would then read the first one's result as the take.
import { studioActionDeclaration } from "../studio-actions.js";
import { analyzePacing, paceSegments } from "../ardy/pace.js";
import { characterOf, fail } from "./shared.js";

const input = (required, optional = {}) => ({ type: "object", properties: { ...required, ...optional }, required: Object.keys(required), additionalProperties: false });

export const declarations = Object.freeze([
	{ ...studioActionDeclaration("motion.readPace"), kind: "job", domain: null,
		input: input({ characterId: { type: "string", minLength: 1, maxLength: 128 } }) },
	{ ...studioActionDeclaration("motion.tightenPace"), kind: "mutation", undoDomain: "motion",
		input: input({ characterId: { type: "string", minLength: 1, maxLength: 128 } }, { speedup: { type: "number", minimum: 1, maximum: 2 } }) },
]);

export function register(registry, ports) {
	const owner = () => ports.storeDomain?.("motion");
	const mounted = () => Boolean(owner()) || "The motion document owner is not mounted.";

	/** The take a pace is measured on, or null when this character has none. */
	const sourceTake = (characterId) => {
		const domain = owner();
		if (!domain) return null;
		return (domain.fullMotionFor ?? domain.motionFor)?.(characterId) ?? null;
	};

	const paceOf = (characterId) => {
		const take = sourceTake(characterId);
		if (!take) fail("TARGET_NOT_READY", "This character has no take to measure; generate or load one first.");
		return { take, pacing: analyzePacing(take, { fps: take.fps }) };
	};

	registry.register({ ...declarations[0], available: mounted,
		run: ({ characterId }) => {
			characterOf(ports, characterId);
			const { pacing } = paceOf(characterId);
			return {
				affectedIds: [],
				summary: pacing.verdict === "even"
					? `The take is evenly paced over ${pacing.seconds.toFixed(2)}s.`
					: `The take reads ${pacing.verdict} over ${pacing.seconds.toFixed(2)}s: ${(pacing.stillShare * 100).toFixed(0)}% of its frames stand still, ${pacing.meanMovingSpeed.toFixed(2)} m/s while moving.`,
				output: { frames: pacing.frames, fps: pacing.fps, seconds: pacing.seconds, verdict: pacing.verdict, issues: pacing.issues,
					stillShare: pacing.stillShare, leadingStillFrames: pacing.leadingStillFrames, trailingStillFrames: pacing.trailingStillFrames,
					meanMovingSpeed: pacing.meanMovingSpeed },
			};
		} });

	registry.register({ ...declarations[1], available: mounted,
		run: ({ characterId, speedup }) => {
			characterOf(ports, characterId);
			const { take, pacing } = paceOf(characterId);
			// A well-paced take is a real, successful answer, not a failure: it is
			// reported as a no-op with no affected ids, so nothing enters the
			// history and undo cannot step back to a change that never happened.
			const plan = paceSegments(take, { fps: take.fps, speedup });
			if (!plan) return { affectedIds: [], output: { changed: false, verdict: pacing.verdict },
				summary: "That take is already well paced; nothing was changed." };
			// `editSegments` is the studio's own writer for this field: it re-renders
			// the take through renderMotionEdit (slerped rotations, positions
			// regenerated by forward kinematics) and remaps the IK keys and prompt
			// clips onto the new timeline, so nothing authored drifts off its pose.
			owner().editSegments(characterId, plan.segments);
			return {
				affectedIds: [characterId],
				output: { changed: true, segments: plan.segments, speed: plan.speed,
					trimmedLeadFrames: plan.trimmedLeadFrames, trimmedTailFrames: plan.trimmedTailFrames,
					before: { frames: pacing.frames, seconds: pacing.seconds }, verdict: pacing.verdict },
				summary: plan.summary,
			};
		} });
}
